name = "HashArrayMappedTries"
uuid = "076d061b-32b6-4027-95e0-9a2c6f6d7e74"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
